<?php

require_once './class/menu.php';

class head {

    function __construct() {
        $HEAD = "<head>
        <meta charset='UTF-8'>
        <meta name='viewport'>
        <!-- content='width=device-width, user-scalable=no, initial-scale=1, maximum-scale=1.2'-->
        <link rel='shortcut icon' href='img/icon/icpr.png'>
        <title>Delivery</title>
        <!--CSS-->
        <link rel='stylesheet' type='text/css' href='css/camp.css'>
        <link rel='stylesheet' type='text/css' href='css/style.css'>
        <!--JS-->
        <!-- <link type='text/javascript' href='js/basic.js'> -->
        <script charset='utf-8' type='text/javascript' src='js/basic.js' defer='defer'></script>
        <script charset='utf-8' type='text/javascript' src='js/cep.js' defer='defer'></script>
        <script charset='utf-8' type='text/javascript' src='js/valcpf.js' defer='defer'></script>

    </head>";
        echo $HEAD;
        return;
    }

}
?>